const I18N={en:{brand:'Al Rams Laundry',staffLogin:'Staff sign in',adminLogin:'Admin sign in',username:'Username',password:'Password',signin:'Sign in',hours:'Open 8 AM–11 PM',admin:'Admin',staff:'Staff',logout:'Logout',newOrder:'New order',phone:'Customer phone',name:'Customer name',expected:'Expected completion',notes:'Notes',addItems:'Add items',category:'Category',item:'Item',size:'Size',service:'Service',quantity:'Quantity',dimensions:'Width × height (m)',add:'Add to basket',todayOrders:'Today’s orders',search:'Phone or order reference',basket:'Order basket',empty:'No items yet',subtotal:'Subtotal',vat:'VAT 5%',total:'Total',paid:'Paid',payment:'Payment method',confirm:'Confirm order',adminDashboard:'Admin dashboard',export:'Export CSV',todaySales:'Today’s gross',paidSales:'Paid today',outstanding:'Outstanding',allOrders:'All orders',reference:'Reference',customer:'Customer',status:'Status',balance:'Balance',created:'Created',statusSummary:'Status summary',paymentSummary:'Payments today',whatsapp:'WhatsApp notifications',all:'All',print:'Print',recordPayment:'Record payment'},ar:{brand:'مغسلة الرمس',staffLogin:'دخول الموظفين',adminLogin:'دخول الإدارة',username:'اسم المستخدم',password:'كلمة المرور',signin:'دخول',hours:'مفتوح من 8 صباحاً إلى 11 مساءً',admin:'الإدارة',staff:'الموظفين',logout:'خروج',newOrder:'طلب جديد',phone:'هاتف العميل',name:'اسم العميل',expected:'موعد الإنجاز المتوقع',notes:'ملاحظات',addItems:'إضافة القطع',category:'القسم',item:'القطعة',size:'المقاس',service:'الخدمة',quantity:'الكمية',dimensions:'العرض × الطول (م)',add:'إضافة للسلة',todayOrders:'الطلبات',search:'الهاتف أو رقم الطلب',basket:'سلة الطلب',empty:'لا توجد قطع',subtotal:'المجموع',vat:'ضريبة 5%',total:'الإجمالي',paid:'المدفوع',payment:'طريقة الدفع',confirm:'تأكيد الطلب',adminDashboard:'لوحة الإدارة',export:'تصدير CSV',todaySales:'مبيعات اليوم',paidSales:'مدفوع اليوم',outstanding:'المبالغ المتبقية',allOrders:'كل الطلبات',reference:'رقم الطلب',customer:'العميل',status:'الحالة',balance:'المتبقي',created:'التاريخ',statusSummary:'ملخص الحالات',paymentSummary:'دفعات اليوم',whatsapp:'إشعارات واتساب',all:'الكل',print:'طباعة',recordPayment:'تسجيل دفعة'}};
let lang=localStorage.getItem('laundry_lang')||'en',csrf='';
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-t]').forEach(e=>e.textContent=I18N[lang][e.dataset.t]||e.dataset.t);document.querySelectorAll('[data-t-placeholder]').forEach(e=>e.placeholder=I18N[lang][e.dataset.tPlaceholder]||'');const b=document.getElementById('lang');if(b)b.textContent=lang==='en'?'AR':'EN'}
function toggleLang(){lang=lang==='en'?'ar':'en';localStorage.setItem('laundry_lang',lang);applyLang();if(window.render)render()}
const money=c=>'AED '+((Number(c)||0)/100).toFixed(2);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url,opt={}){opt.headers={'Content-Type':'application/json',...(opt.headers||{})};if(opt.method&&opt.method!=='GET')opt.headers['X-CSRF-Token']=csrf;const r=await fetch(url,opt);const d=await r.json().catch(()=>({error:r.statusText}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
async function session(requiredRole){const d=await api('/api/me');if(d.authenticated&&(!requiredRole||d.user.role===requiredRole)){csrf=d.user.csrf;document.getElementById('login').classList.add('hidden');return d.user}return null}
async function login(ev,requiredRole){ev.preventDefault();try{const d=await api('/api/login',{method:'POST',body:JSON.stringify({username:username.value,password:password.value})});if(requiredRole&&d.user.role!==requiredRole){csrf=d.csrf;await api('/api/logout',{method:'POST',body:'{}'});throw new Error('Admin access required')}csrf=d.csrf;document.getElementById('login').classList.add('hidden');location.reload()}catch(e){loginError.textContent=e.message}}
async function logout(){await api('/api/logout',{method:'POST',body:'{}'}).catch(()=>{});location.reload()}
document.addEventListener('DOMContentLoaded',()=>{applyLang();document.getElementById('lang')?.addEventListener('click',toggleLang);document.getElementById('logout')?.addEventListener('click',logout)});
