let catalog={},basket=[],orders=[];const statusNames={received:['Received','تم الاستلام'],washing:['Washing','غسيل'],drying:['Drying','تجفيف'],ironing:['Ironing','كوي'],ready:['Ready','جاهز'],collected:['Collected','تم التسليم'],cancelled:['Cancelled','ملغي']};const categoryImages={'ملابس رجالية':'assets/categories/mens.webp','ملابس نسائية':'assets/categories/womens.webp','إكسسوارات ومفروشات':'assets/categories/furnishings.webp','ملابس أطفال':'assets/categories/kids.webp','أحذية':'assets/categories/shoes.webp'};const itemImages={'كندورة':'kandura','غترة':'ghutra','فانيلة داخلية':'undershirt','فانيلة رياضية':'sports-vest','بنطلون':'trousers','شورت رياضي':'sports-shorts','شورت داخلي':'underwear-shorts','قميص/كوت':'shirt-coat','بدلة عسكرية':'military-uniform','بشت شتوي':'winter-bisht','عباية':'abaya','شيلة':'shayla','فستان نسائي':'womens-dress','مخدة':'pillow','كفر المخدة':'pillow-cover','سجادة (م2)':'carpet','الفوطة/المنشفة':'towel','بطانيات':'blankets','ستائر':'curtains','كفر سرير':'bed-cover','ملابس أطفال':'kids-clothes','حذاء رجالي':'mens-shoes','حذاء نسائي':'womens-shoes','جوراب':'socks','حذاء أطفال':'kids-shoes'};
const $=id=>document.getElementById(id);function node(){let n=catalog[$('category').value]?.[$('item').value];if(n?.sizes)n=n.sizes[$('size').value];return n||{}}
function renderCategoryCards(){$('categoryCards').innerHTML=Object.keys(catalog).map(x=>`<button type="button" class="photo-card ${$('category').value===x?'selected':''}" onclick="chooseCategory('${x.replace(/'/g,"\\'")}')"><img src="${categoryImages[x]}" alt=""><span>${esc(catLabel(x))}</span></button>`).join('')}
function renderItemCards(){const cat=$('category').value,c=catalog[cat]||{};$('itemCards').innerHTML=Object.keys(c).map(x=>`<button type="button" class="photo-card ${$('item').value===x?'selected':''}" onclick="chooseItem('${x.replace(/'/g,"\\'")}')"><img src="assets/items/${itemImages[x]}.webp" alt="${esc(itemLabel(x))}"><span>${esc(itemLabel(x))}</span></button>`).join('')}
function chooseCategory(value){$('category').value=$('category').value===value?'':value;fillItems();renderCategoryCards()}
function chooseItem(value){$('item').value=$('item').value===value?'':value;fillSizes();renderItemCards()}
function fillCategories(selected=''){$('category').innerHTML='<option value=""></option>'+Object.keys(catalog).map(x=>`<option value="${esc(x)}">${esc(catLabel(x))}</option>`).join('');$('category').value=selected&&catalog[selected]?selected:'';fillItems();renderCategoryCards()}
function fillItems(selected=''){const c=catalog[$('category').value]||{};$('item').innerHTML='<option value=""></option>'+Object.keys(c).map(x=>`<option value="${esc(x)}">${esc(itemLabel(x))}</option>`).join('');$('item').value=selected&&c[selected]?selected:'';fillSizes();renderItemCards()}
function fillSizes(){const n=catalog[$('category').value]?.[$('item').value];$('sizeWrap').classList.toggle('hidden',!n?.sizes);$('size').innerHTML=n?.sizes?Object.keys(n.sizes).map(x=>`<option>${esc(x)}</option>`).join(''):'';$('dimensions').classList.toggle('hidden',$('item').value!=='سجادة (م2)');fillServices()}
function fillServices(selected){const n=node(), services=Object.keys(n);if(n['غسيل']!=null&&n['كوي']!=null&&!services.includes('غسيل + كوي'))services.push('غسيل + كوي');$('service').innerHTML=services.map(x=>`<option value="${esc(x)}">${esc(serviceLabel(x))}</option>`).join('');if(selected)$('service').value=selected;$('addItem').disabled=!services.length}
function calcLine(x){let n=catalog[x.category][x.item];if(n.sizes)n=n.sizes[x.size];let p=n[x.service]??(Number(n['غسيل'])+Number(n['كوي']));let f=x.quantity;if(x.item==='سجادة (م2)')f*=x.width*x.height;return Math.round(p*f*100)}
function updateConfirm(){ $('confirm').disabled=!($('customerName').value.trim().length>1&&$('phone').value.trim()&&basket.length) }
function renderBasket(){let sub=basket.reduce((a,x)=>a+calcLine(x),0);$('basket').innerHTML=basket.length?basket.map((x,i)=>`<div class="basket-row"><div><b>${esc(itemLabel(x.item))}</b><div class="tiny">${esc(serviceLabel(x.service))} ${x.size?'- '+esc(x.size):''} × ${x.quantity}</div></div><b class="price">${money(calcLine(x))}</b><button class="btn danger" onclick="basket.splice(${i},1);renderBasket()">×</button></div>`).join(''):`<p class="tiny">${I18N[lang].empty}</p>`;$('subtotal').textContent=money(sub);$('total').textContent=money(sub);updateConfirm()}
function addItem(){try{let x={category:$('category').value,item:$('item').value,size:$('size').value||'',service:$('service').value,quantity:Number($('quantity').value),width:Number($('width').value),height:Number($('height').value)};if(!x.category||!x.item||!x.service)throw Error(lang==='ar'?'اختر القسم والقطعة والخدمة':'Choose a category, item, and service');if(!x.quantity||x.quantity<1)throw Error('Enter quantity');if(x.item==='سجادة (م2)'&&(!x.width||!x.height))throw Error('Enter carpet dimensions');basket.push(x);$('itemError').textContent='';renderBasket()}catch(e){$('itemError').textContent=e.message}}
async function findCustomer(){if($('phone').value.replace(/\D/g,'').length<9)return;try{const d=await api('/api/customer?phone='+encodeURIComponent($('phone').value));if(d.customer){$('customerName').value=d.customer.name;$('customerHint').textContent=`${d.orders.length} ${I18N[lang].previousOrders}`}else $('customerHint').textContent=I18N[lang].newCustomer;updateConfirm()}catch(e){$('customerHint').textContent=e.message}}
async function createOrder(){try{$('confirm').disabled=true;$('orderError').textContent='';const d=await api('/api/orders',{method:'POST',body:JSON.stringify({customer_name:$('customerName').value,phone:$('phone').value,expected_at:$('expected').value,notes:$('notes').value,items:basket,paid:Number($('paid').value||0),payment_method:$('payment').value,client_key:crypto.randomUUID()})});basket=[];renderBasket();receipt(d.order);await loadOrders();$('customerName').value=$('phone').value=$('notes').value='';$('paid').value=0}catch(e){$('orderError').textContent=e.message;updateConfirm()}}
function receipt(o){$('receipt').innerHTML=`<h1>مغسلة الرمس<br><small>Al Rams Laundry</small></h1><p>Al Rams, Ras Al Khaimah · 8 AM–11 PM</p><hr><p><b>${esc(o.order_ref)}</b><br>${esc(o.customer_name)} · ${esc(o.phone.slice(0,4)+'*****'+o.phone.slice(-3))}<br>${esc(o.created_at)}</p><table><tr><th>Item / القطعة</th><th>Qty</th><th>Total</th></tr>${o.items.map(x=>`<tr><td>${esc(itemLabel(x.item))} — ${esc(serviceLabel(x.service))}</td><td>${x.quantity}</td><td>${money(x.line_cents)}</td></tr>`).join('')}</table><hr><p>Subtotal: ${money(o.subtotal_cents)}<br><b>Total: ${money(o.total_cents)}</b><br>Paid: ${money(o.paid_cents)}<br>Balance: ${money(o.balance_cents)}</p><p>Thank you · شكراً لكم</p>`;window.print()}
async function loadOrders(){const d=await api('/api/orders?q='+encodeURIComponent($('orderSearch').value));orders=d.orders;render()}
function render(){applyLang();$('orders').innerHTML=orders.map(o=>`<article class="order-row"><div class="order-head"><div><b>${esc(o.order_ref)} · ${esc(o.customer_name)}</b><div class="tiny">${esc(o.phone)} · ${o.items.map(x=>esc(itemLabel(x.item))).join(', ')}</div></div><span class="status ${o.status}">${statusNames[o.status]?.[lang==='ar'?1:0]||o.status}</span></div><div><b>${money(o.total_cents)}</b> · ${I18N[lang].balance}: ${money(o.balance_cents)}</div><div class="order-actions">${o.status!=='cancelled'&&o.status!=='collected'?`<button class="btn" onclick="advance(${o.id},'${o.status}')">${statusNames[nextStatus(o.status)]?.[lang==='ar'?1:0]||''}</button><button class="btn danger" onclick="setStatus(${o.id},'cancelled')">${statusNames.cancelled[lang==='ar'?1:0]}</button>`:''}${o.balance_cents>0&&o.status!=='cancelled'?`<button class="btn gold" onclick="pay(${o.id},${o.balance_cents})">${I18N[lang].recordPayment}</button>`:''}<button class="btn secondary" onclick='receipt(${JSON.stringify(o).replace(/'/g,"&#39;")})'>${I18N[lang].print}</button></div></article>`).join('')||`<p class="tiny">${I18N[lang].empty}</p>`}
function nextStatus(s){return ({received:'washing',washing:'drying',drying:'ironing',ironing:'ready',ready:'collected'})[s]||s}async function advance(id,s){return setStatus(id,nextStatus(s))}async function setStatus(id,status){try{await api(`/api/orders/${id}/status`,{method:'POST',body:JSON.stringify({status})});loadOrders()}catch(e){alert(e.message)}}async function pay(id,balance){const amount=prompt('Amount / المبلغ',(balance/100).toFixed(2));if(!amount)return;const method=prompt('cash, card, bank','cash');try{await api(`/api/orders/${id}/payment`,{method:'POST',body:JSON.stringify({amount:Number(amount),method,client_key:crypto.randomUUID()})});loadOrders()}catch(e){alert(e.message)}}
window.render=render;window.onLanguageChanged=()=>{const c=$('category').value,i=$('item').value,z=$('size').value,s=$('service').value;fillCategories(c);fillItems(i);if(z)$('size').value=z;fillServices(s);renderBasket();render()};document.addEventListener('DOMContentLoaded',async()=>{$('loginForm').onsubmit=e=>login(e);if(!await session())return;catalog=await api('/api/catalog');fillCategories();await loadOrders();$('category').onchange=()=>fillItems();$('item').onchange=fillSizes;$('size').onchange=()=>fillServices();$('addItem').onclick=addItem;$('confirm').onclick=createOrder;$('phone').onblur=findCustomer;$('customerName').oninput=updateConfirm;$('phone').oninput=updateConfirm;$('orderSearch').oninput=()=>{clearTimeout(window.sq);window.sq=setTimeout(loadOrders,300)};$('expected').value=new Date(Date.now()+86400000).toISOString().slice(0,16)});

// Enhanced fast-entry and order-management workflow.
let orderFilter='',editingOrderId=null,businessSettings={};
const popularItems=['كندورة','غترة','عباية','بنطلون','ملابس أطفال','حذاء رجالي'];
function allItems(){return Object.entries(catalog).flatMap(([category,items])=>Object.keys(items).map(item=>({category,item})))}
function itemBasePrice(category,item){let n=catalog[category][item],values=[];if(n.sizes)Object.values(n.sizes).forEach(s=>values.push(...Object.values(s)));else values=Object.values(n);return Math.min(...values.map(Number))}
function renderQuickItems(){if(!$('quickItems'))return;let recent=JSON.parse(localStorage.getItem('laundry_recent_items')||'[]').slice(0,5),names=[...new Set([...recent,...popularItems])];$('quickItems').innerHTML=`<p class="picker-step">${lang==='ar'?'الأكثر استخداماً والأخيرة':'Popular & recent'}</p><div class="quick-strip">${names.map(name=>{let found=allItems().find(x=>x.item===name);return found?`<button type="button" onclick="quickChoose('${found.category}','${found.item}')"><img src="assets/items/${itemImages[name]}.webp" alt=""><span>${esc(itemLabel(name))}</span><b>${money(itemBasePrice(found.category,name)*100)}+</b></button>`:''}).join('')}</div>`}
function quickChoose(category,item){$('category').value=category;fillItems(item);renderCategoryCards();document.querySelector('.picker-options')?.scrollIntoView({behavior:'smooth',block:'center'})}
function renderItemCards(){const cat=$('category').value,c=catalog[cat]||{},term=($('itemSearch')?.value||'').trim().toLowerCase();if(!cat){$('itemCards').innerHTML=`<p class="notice">${lang==='ar'?'اختر القسم أولاً':'Choose a category first'}</p>`;return}$('itemCards').innerHTML=Object.keys(c).filter(x=>!term||itemLabel(x).toLowerCase().includes(term)||x.includes(term)).map(x=>`<button type="button" class="photo-card ${$('item').value===x?'selected':''}" onclick="chooseItem('${x.replace(/'/g,"\\'")}')"><img src="assets/items/${itemImages[x]}.webp" alt="${esc(itemLabel(x))}"><span>${esc(itemLabel(x))}<small>${lang==='ar'?'من':'from'} ${money(itemBasePrice(cat,x)*100)}</small></span></button>`).join('')||`<p class="notice">${lang==='ar'?'لا توجد نتائج':'No matching items'}</p>`}
function fillServices(selected){const n=node(),services=Object.keys(n);if(n['غسيل']!=null&&n['كوي']!=null&&!services.includes('غسيل + كوي'))services.push('غسيل + كوي');$('service').innerHTML=services.map(x=>`<option value="${esc(x)}">${esc(serviceLabel(x))}</option>`).join('');if(selected&&services.includes(selected))$('service').value=selected;$('addItem').disabled=!services.length;renderServiceButtons()}
function servicePrice(service){let n=node(),p=n[service]??(Number(n['غسيل'])+Number(n['كوي']));return Number(p)||0}
function renderServiceButtons(){if(!$('serviceButtons'))return;let selected=$('service').value;$('serviceButtons').innerHTML=[...$('service').options].map(o=>`<button type="button" class="${o.value===selected?'selected':''}" onclick="selectService('${o.value}')"><b>${esc(serviceLabel(o.value))}</b><span>${money(servicePrice(o.value)*100)}</span></button>`).join('')}
function selectService(value){$('service').value=value;renderServiceButtons()}
function changeQty(change){$('quantity').value=Math.max(1,Math.min(999,Number($('quantity').value||1)+change))}
function addItem(){try{let x={category:$('category').value,item:$('item').value,size:$('size').value||'',service:$('service').value,quantity:Number($('quantity').value),width:Number($('width').value),height:Number($('height').value)};if(!x.category||!x.item||!x.service)throw Error(lang==='ar'?'اختر القسم والقطعة والخدمة':'Choose a category, item, and service');if(!x.quantity||x.quantity<1)throw Error(lang==='ar'?'أدخل الكمية':'Enter quantity');if(x.item==='سجادة (م2)'&&(!x.width||!x.height))throw Error(lang==='ar'?'أدخل قياس السجادة':'Enter carpet dimensions');basket.push(x);let recent=JSON.parse(localStorage.getItem('laundry_recent_items')||'[]').filter(v=>v!==x.item);recent.unshift(x.item);localStorage.setItem('laundry_recent_items',JSON.stringify(recent.slice(0,8)));$('quantity').value=1;$('itemError').textContent='';renderBasket();renderQuickItems()}catch(e){$('itemError').textContent=e.message}}
async function findCustomer(){if($('phone').value.replace(/\D/g,'').length<9)return;try{const d=await api('/api/customer?phone='+encodeURIComponent($('phone').value));if(d.customer){$('customerName').value=d.customer.name;$('customerHint').textContent=`${d.orders.length} ${I18N[lang].previousOrders}`;$('customerProfile').classList.remove('hidden');$('customerProfile').innerHTML=`<div><b>${lang==='ar'?'سجل العميل':'Customer history'}</b><span>${d.stats.visits} ${lang==='ar'?'زيارات':'visits'}</span><span>${money(d.stats.spent_cents)} ${lang==='ar'?'إجمالي':'spent'}</span><span>${money(d.stats.unpaid_cents)} ${lang==='ar'?'متبقي':'unpaid'}</span><span>${d.stats.preferred_item?esc(itemLabel(d.stats.preferred_item)):''}</span></div><label>${lang==='ar'?'ملاحظة مهمة':'Important note'}<textarea id="customerImportantNote">${esc(d.customer.important_notes||'')}</textarea></label><button class="btn secondary" onclick="saveCustomerNote(${d.customer.id})">${lang==='ar'?'حفظ الملاحظة':'Save note'}</button>`}else{$('customerHint').textContent=I18N[lang].newCustomer;$('customerProfile').classList.add('hidden')}updateConfirm()}catch(e){$('customerHint').textContent=e.message}}
async function saveCustomerNote(id){try{await api(`/api/customers/${id}/notes`,{method:'POST',body:JSON.stringify({notes:$('customerImportantNote').value})});$('customerHint').textContent=lang==='ar'?'تم حفظ الملاحظة':'Note saved'}catch(e){alert(e.message)}}
async function createOrder(){try{$('confirm').disabled=true;$('orderError').textContent='';let payload={customer_name:$('customerName').value,phone:$('phone').value,expected_at:$('expected').value,notes:$('notes').value,items:basket,paid:Number($('paid').value||0),payment_method:$('payment').value,client_key:crypto.randomUUID()};let url=editingOrderId?`/api/orders/${editingOrderId}/edit`:'/api/orders';const d=await api(url,{method:'POST',body:JSON.stringify(payload)});editingOrderId=null;basket=[];renderBasket();receipt(d.order);await loadOrders();$('customerName').value=$('phone').value=$('notes').value='';$('paid').value=0;$('confirm').textContent=I18N[lang].confirm}catch(e){$('orderError').textContent=e.message;updateConfirm()}}
function editOrder(id){let o=orders.find(x=>x.id===id);if(!o||o.status!=='received')return;editingOrderId=id;basket=o.items.map(x=>({category:x.category,item:x.item,size:x.size||'',service:x.service,quantity:x.quantity,width:Number(x.width||0),height:Number(x.height||0)}));$('phone').value=o.phone;$('customerName').value=o.customer_name;$('expected').value=(o.expected_at||'').slice(0,16);$('notes').value=o.notes||'';renderBasket();$('confirm').textContent=lang==='ar'?'حفظ التعديلات':'Save changes';window.scrollTo({top:0,behavior:'smooth'})}
async function sendWhatsApp(id,type='payment_reminder'){try{await api(`/api/orders/${id}/whatsapp`,{method:'POST',body:JSON.stringify({type})});alert(lang==='ar'?'تمت إضافة الرسالة للإرسال':'Message queued')}catch(e){alert(e.message)}}
async function loadOrders(){let q='?q='+encodeURIComponent($('orderSearch').value);if(orderFilter.startsWith('due:'))q+='&due='+orderFilter.split(':')[1];else if(orderFilter)q+='&status='+orderFilter;const d=await api('/api/orders'+q);orders=d.orders;render()}
function renderTabs(){let tabs=[['',I18N[lang].all],['received',statusNames.received[lang==='ar'?1:0]],['washing',statusNames.washing[lang==='ar'?1:0]],['ironing',statusNames.ironing[lang==='ar'?1:0]],['ready',statusNames.ready[lang==='ar'?1:0]],['collected',statusNames.collected[lang==='ar'?1:0]],['due:today',lang==='ar'?'مستحق اليوم':'Due today'],['due:overdue',lang==='ar'?'متأخر':'Overdue']];$('orderTabs').innerHTML=tabs.map(([v,l])=>`<button class="${orderFilter===v?'active':''}" onclick="orderFilter='${v}';loadOrders()">${l}</button>`).join('')}
function render(){applyLang();renderTabs();$('orders').innerHTML=orders.map(o=>{let overdue=o.expected_at&&new Date(o.expected_at)<new Date()&&!['collected','cancelled'].includes(o.status);return`<article class="order-row ${overdue?'overdue':''}"><div class="order-head"><div><b>${esc(o.order_ref)} · ${esc(o.customer_name)}</b><div class="tiny">${esc(o.phone)} · ${o.items.map(x=>esc(itemLabel(x.item))).join(', ')}</div>${o.expected_at?`<div class="tiny">${overdue?'⚠️ ':''}${new Date(o.expected_at).toLocaleString()}</div>`:''}</div><span class="status ${o.status}">${statusNames[o.status]?.[lang==='ar'?1:0]||o.status}</span></div><div><b>${money(o.total_cents)}</b> · ${I18N[lang].paid}: ${money(o.paid_cents)} · ${I18N[lang].balance}: ${money(o.balance_cents)}</div><div class="order-actions">${o.status!=='cancelled'&&o.status!=='collected'?`<button class="btn" onclick="advance(${o.id},'${o.status}')">${statusNames[nextStatus(o.status)]?.[lang==='ar'?1:0]||''}</button><button class="btn danger" onclick="setStatus(${o.id},'cancelled')">${statusNames.cancelled[lang==='ar'?1:0]}</button>`:''}${o.status==='received'?`<button class="btn secondary" onclick="editOrder(${o.id})">✏️ ${lang==='ar'?'تعديل':'Edit'}</button>`:''}${o.balance_cents>0&&o.status!=='cancelled'?`<button class="btn gold" onclick="pay(${o.id},${o.balance_cents})">${I18N[lang].recordPayment}</button>`:''}<button class="btn secondary" onclick='receipt(${JSON.stringify(o).replace(/'/g,"&#39;")})'>🖨 ${I18N[lang].print}</button><button class="btn secondary" onclick="sendWhatsApp(${o.id},'${o.status==='ready'?'ready':'payment_reminder'}')">💬 WhatsApp</button></div></article>`}).join('')||`<p class="tiny">${I18N[lang].empty}</p>`}
const oldLanguageChanged=window.onLanguageChanged;window.onLanguageChanged=()=>{oldLanguageChanged?.();renderQuickItems();renderServiceButtons();renderTabs()};
document.addEventListener('DOMContentLoaded',()=>setTimeout(async()=>{if($('itemSearch'))$('itemSearch').oninput=renderItemCards;try{businessSettings=(await api('/api/business-settings')).settings}catch{}renderQuickItems();renderServiceButtons();renderTabs()},400));

function receipt(o){let phone=businessSettings.business_phone||'',tax=businessSettings.tax_number||'',footer=businessSettings.receipt_footer||'Thank you · شكراً لكم';$('receipt').innerHTML=`<h1>مغسلة الرمس<br><small>Al Rams Laundry</small></h1><p>Al Rams, Ras Al Khaimah · 8 AM–11 PM<br>${phone?esc(phone)+'<br>':''}${tax?'TRN: '+esc(tax):''}</p><hr><p><b>Receipt / إيصال: ${esc(o.order_ref)}</b><br>${esc(o.customer_name)} · ${esc(o.phone.slice(0,4)+'*****'+o.phone.slice(-3))}<br>${esc(o.created_at)}${o.expected_at?'<br>Due / الاستلام: '+esc(o.expected_at):''}</p><table><tr><th>Item / القطعة</th><th>Qty</th><th>Total</th></tr>${o.items.map(x=>`<tr><td>${esc(itemLabel(x.item))} — ${esc(serviceLabel(x.service))}</td><td>${x.quantity}</td><td>${money(x.line_cents)}</td></tr>`).join('')}</table><hr><p>Subtotal: ${money(o.subtotal_cents)}<br>${o.discount_cents?'Discount: −'+money(o.discount_cents)+'<br>':''}<b>Total: ${money(o.total_cents)}</b><br>Paid: ${money(o.paid_cents)}<br>Balance: ${money(o.balance_cents)}</p><p>${esc(footer)}</p>`;window.print()}
