let catalog={},basket=[],orders=[];const statusNames={received:['Received','تم الاستلام'],washing:['Washing','غسيل'],drying:['Drying','تجفيف'],ironing:['Ironing','كوي'],ready:['Ready','جاهز'],collected:['Collected','تم التسليم'],cancelled:['Cancelled','ملغي']};
const $=id=>document.getElementById(id);function node(){let n=catalog[$('category').value]?.[$('item').value];if(n?.sizes)n=n.sizes[$('size').value];return n||{}}
function fillCategories(selected){$('category').innerHTML=Object.keys(catalog).map(x=>`<option value="${esc(x)}">${esc(catLabel(x))}</option>`).join('');if(selected)$('category').value=selected;fillItems()}
function fillItems(selected){const c=catalog[$('category').value]||{};$('item').innerHTML=Object.keys(c).map(x=>`<option value="${esc(x)}">${esc(itemLabel(x))}</option>`).join('');if(selected)$('item').value=selected;fillSizes()}
function fillSizes(){const n=catalog[$('category').value]?.[$('item').value];$('sizeWrap').classList.toggle('hidden',!n?.sizes);$('size').innerHTML=n?.sizes?Object.keys(n.sizes).map(x=>`<option>${esc(x)}</option>`).join(''):'';$('dimensions').classList.toggle('hidden',$('item').value!=='سجادة (م2)');fillServices()}
function fillServices(selected){const n=node(), services=Object.keys(n);if(n['غسيل']!=null&&n['كوي']!=null&&!services.includes('غسيل + كوي'))services.push('غسيل + كوي');$('service').innerHTML=services.map(x=>`<option value="${esc(x)}">${esc(serviceLabel(x))}</option>`).join('');if(selected)$('service').value=selected}
function calcLine(x){let n=catalog[x.category][x.item];if(n.sizes)n=n.sizes[x.size];let p=n[x.service]??(Number(n['غسيل'])+Number(n['كوي']));let f=x.quantity;if(x.item==='سجادة (م2)')f*=x.width*x.height;return Math.round(p*f*100)}
function updateConfirm(){ $('confirm').disabled=!($('customerName').value.trim().length>1&&$('phone').value.trim()&&basket.length) }
function renderBasket(){let sub=basket.reduce((a,x)=>a+calcLine(x),0),v=Math.round(sub*.05);$('basket').innerHTML=basket.length?basket.map((x,i)=>`<div class="basket-row"><div><b>${esc(itemLabel(x.item))}</b><div class="tiny">${esc(serviceLabel(x.service))} ${x.size?'- '+esc(x.size):''} × ${x.quantity}</div></div><b class="price">${money(calcLine(x))}</b><button class="btn danger" onclick="basket.splice(${i},1);renderBasket()">×</button></div>`).join(''):`<p class="tiny">${I18N[lang].empty}</p>`;$('subtotal').textContent=money(sub);$('vat').textContent=money(v);$('total').textContent=money(sub+v);updateConfirm()}
function addItem(){try{let x={category:$('category').value,item:$('item').value,size:$('size').value||'',service:$('service').value,quantity:Number($('quantity').value),width:Number($('width').value),height:Number($('height').value)};if(!x.quantity||x.quantity<1)throw Error('Enter quantity');if(x.item==='سجادة (م2)'&&(!x.width||!x.height))throw Error('Enter carpet dimensions');basket.push(x);$('itemError').textContent='';renderBasket()}catch(e){$('itemError').textContent=e.message}}
async function findCustomer(){if($('phone').value.replace(/\D/g,'').length<9)return;try{const d=await api('/api/customer?phone='+encodeURIComponent($('phone').value));if(d.customer){$('customerName').value=d.customer.name;$('customerHint').textContent=`${d.orders.length} ${I18N[lang].previousOrders}`}else $('customerHint').textContent=I18N[lang].newCustomer;updateConfirm()}catch(e){$('customerHint').textContent=e.message}}
async function createOrder(){try{$('confirm').disabled=true;$('orderError').textContent='';const d=await api('/api/orders',{method:'POST',body:JSON.stringify({customer_name:$('customerName').value,phone:$('phone').value,expected_at:$('expected').value,notes:$('notes').value,items:basket,paid:Number($('paid').value||0),payment_method:$('payment').value,client_key:crypto.randomUUID()})});basket=[];renderBasket();receipt(d.order);await loadOrders();$('customerName').value=$('phone').value=$('notes').value='';$('paid').value=0}catch(e){$('orderError').textContent=e.message;updateConfirm()}}
function receipt(o){$('receipt').innerHTML=`<h1>مغسلة الرمس<br><small>Al Rams Laundry</small></h1><p>Al Rams, Ras Al Khaimah · 8 AM–11 PM</p><hr><p><b>${esc(o.order_ref)}</b><br>${esc(o.customer_name)} · ${esc(o.phone.slice(0,4)+'*****'+o.phone.slice(-3))}<br>${esc(o.created_at)}</p><table><tr><th>Item / القطعة</th><th>Qty</th><th>Total</th></tr>${o.items.map(x=>`<tr><td>${esc(itemLabel(x.item))} — ${esc(serviceLabel(x.service))}</td><td>${x.quantity}</td><td>${money(x.line_cents)}</td></tr>`).join('')}</table><hr><p>Subtotal: ${money(o.subtotal_cents)}<br>VAT 5%: ${money(o.vat_cents)}<br><b>Total: ${money(o.total_cents)}</b><br>Paid: ${money(o.paid_cents)}<br>Balance: ${money(o.balance_cents)}</p><p>Thank you · شكراً لكم</p>`;window.print()}
async function loadOrders(){const d=await api('/api/orders?q='+encodeURIComponent($('orderSearch').value));orders=d.orders;render()}
function render(){applyLang();$('orders').innerHTML=orders.map(o=>`<article class="order-row"><div class="order-head"><div><b>${esc(o.order_ref)} · ${esc(o.customer_name)}</b><div class="tiny">${esc(o.phone)} · ${o.items.map(x=>esc(itemLabel(x.item))).join(', ')}</div></div><span class="status ${o.status}">${statusNames[o.status]?.[lang==='ar'?1:0]||o.status}</span></div><div><b>${money(o.total_cents)}</b> · ${I18N[lang].balance}: ${money(o.balance_cents)}</div><div class="order-actions">${o.status!=='cancelled'&&o.status!=='collected'?`<button class="btn" onclick="advance(${o.id},'${o.status}')">${statusNames[nextStatus(o.status)]?.[lang==='ar'?1:0]||''}</button><button class="btn danger" onclick="setStatus(${o.id},'cancelled')">${statusNames.cancelled[lang==='ar'?1:0]}</button>`:''}${o.balance_cents>0&&o.status!=='cancelled'?`<button class="btn gold" onclick="pay(${o.id},${o.balance_cents})">${I18N[lang].recordPayment}</button>`:''}<button class="btn secondary" onclick='receipt(${JSON.stringify(o).replace(/'/g,"&#39;")})'>${I18N[lang].print}</button></div></article>`).join('')||`<p class="tiny">${I18N[lang].empty}</p>`}
function nextStatus(s){return ({received:'washing',washing:'drying',drying:'ironing',ironing:'ready',ready:'collected'})[s]||s}async function advance(id,s){return setStatus(id,nextStatus(s))}async function setStatus(id,status){try{await api(`/api/orders/${id}/status`,{method:'POST',body:JSON.stringify({status})});loadOrders()}catch(e){alert(e.message)}}async function pay(id,balance){const amount=prompt('Amount / المبلغ',(balance/100).toFixed(2));if(!amount)return;const method=prompt('cash, card, bank','cash');try{await api(`/api/orders/${id}/payment`,{method:'POST',body:JSON.stringify({amount:Number(amount),method,client_key:crypto.randomUUID()})});loadOrders()}catch(e){alert(e.message)}}
window.render=render;window.onLanguageChanged=()=>{const c=$('category').value,i=$('item').value,z=$('size').value,s=$('service').value;fillCategories(c);fillItems(i);if(z)$('size').value=z;fillServices(s);renderBasket();render()};document.addEventListener('DOMContentLoaded',async()=>{$('loginForm').onsubmit=e=>login(e);if(!await session())return;catalog=await api('/api/catalog');fillCategories();await loadOrders();$('category').onchange=()=>fillItems();$('item').onchange=fillSizes;$('size').onchange=()=>fillServices();$('addItem').onclick=addItem;$('confirm').onclick=createOrder;$('phone').onblur=findCustomer;$('customerName').oninput=updateConfirm;$('phone').oninput=updateConfirm;$('orderSearch').oninput=()=>{clearTimeout(window.sq);window.sq=setTimeout(loadOrders,300)};$('expected').value=new Date(Date.now()+86400000).toISOString().slice(0,16)});
